import Link from "next/link";
import path from "node:path";
import { listNotes } from "@/core/fs";

export const dynamic = "force-dynamic";

/**
 * /learnings — aggregate view of all cluster summaries.
 *
 * Cluster summaries are ordinary markdown notes written by `kb learn` to
 * `<cluster>/_summary.md`. They're identified by `frontmatter.type === "cluster-summary"`,
 * which is more robust than filename matching (the user could rename, and the
 * opt-out mechanism removes this field — both correctly exclude the note from
 * this view).
 *
 * Sorted by mtime desc (latest first) — matches the home page convention.
 */
export default async function LearningsPage() {
  const notes = await listNotes();
  const summaries = notes.filter((n) => n.type === "cluster-summary");

  return (
    <div className="space-y-6 max-w-3xl">
      <header>
        <h1 className="text-2xl font-bold">Learnings</h1>
        <p className="text-sm text-muted-foreground mt-1">
          {summaries.length === 0
            ? "No cluster summaries yet"
            : `${summaries.length} cluster ${summaries.length === 1 ? "summary" : "summaries"}`}
          {" · "}
          generated by{" "}
          <Link href="/organize" className="underline text-primary">
            Organize &amp; learn
          </Link>
        </p>
      </header>

      {summaries.length === 0 ? (
        <div className="rounded-lg border bg-card p-6 text-sm text-muted-foreground space-y-2">
          <p>
            Cluster summaries are written by{" "}
            <code className="font-mono text-xs">kb learn</code> into each
            topical folder as{" "}
            <code className="font-mono text-xs">_summary.md</code>.
          </p>
          <p>
            To see learnings here: run{" "}
            <Link href="/organize" className="underline text-primary">
              Organize
            </Link>{" "}
            to cluster notes into folders, then switch to the{" "}
            <strong>Learn</strong> tab and apply a plan.
          </p>
        </div>
      ) : (
        <ul className="space-y-2">
          {summaries.map((n) => {
            const clusterFolder = path.dirname(n.path);
            const clusterName =
              clusterFolder === "." ? "(root)" : clusterFolder;
            return (
              <li
                key={n.path}
                className="rounded-lg border bg-card p-3 hover:bg-accent/50 transition-colors"
              >
                <Link
                  href={`/notes/${n.path.replace(/\.md$/, "")}`}
                  className="font-semibold text-card-foreground hover:underline"
                >
                  {clusterName}
                </Link>
                <div className="text-xs text-muted-foreground mt-0.5">
                  {n.path} · {new Date(n.mtime).toLocaleString()}
                </div>
                {n.preview && (
                  <div className="text-sm mt-1 text-muted-foreground line-clamp-2">
                    {n.preview}
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
